### ISSUE TITLE
Download output geotiff

### ISSUE THREAD

**Issue by wipfli** [brawer/osmviews#1]
This looks like a great project, @brawer. Is it possible to download the output geotiff somewhere?

**Comment by wipfli** [comment]
https://github.com/brawer/osmviews-py/blob/3e01e25fc2179613e015a1536e02d1f36e413b73/src/osmviews/__init__.py#L20

**Comment by wipfli** [comment]
https://osmviews.toolforge.org/download/osmviews.tiff

**Comment by brawer** [comment]
Since today, there's now (hopefully nice) instructions at https://github.com/brawer/osmviews in a “Downloads” section.
